export type Icon =
  | ''
  | 'add'
  | 'search'
  | 'filter_list'
  | 'view_column'
  | 'close'
  | 'delete_outline'
  | 'save'
  | 'lock'
  | 'email'
  | 'phone'
  | 'perm_identity'
  | 'keyboard_arrow_left'
  | 'keyboard_arrow_right'
  | 'keyboard_arrow_up'
  | 'keyboard_arrow_down'
  | 'library_add';
